services:
  assistant:
    build:
      context: .
      dockerfile: services/assistant/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./services/assistant:/app

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6381:6379"
    volumes:
      - gemini-agent_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "PING"]
      interval: 30s
      timeout: 5s
      retries: 3
volumes:
  gemini-agent_redis_data:
